### ISSUE TITLE
Missing thumbnails pack (Please merge them)

### ISSUE THREAD

**Issue by andiandi13** [libretro-thumbnails/Sega_-_Game_Gear#7]
Hi,

I compiled all missing thumbnails of my own roms collection, with proper folder tree, name, size, and the best quality I found,

Can you please add them to retroarch.

Thank you

[Sega - Game Gear.zip](https://github.com/libretro-thumbnails/Sega_-_Game_Gear/files/4806715/Sega.-.Game.Gear.zip)

**Comment by RobLoach** [comment]
Thanks! Note that you can upload it directly through the GitHub UI. Drag and drop!

**Comment by andiandi13** [comment]
@RobLoach Do you mean drag them in the issue section like I did with the archive ? Because i prefered on archive with all folders tree.

But if you mean update the thumbnails directly in the github project of each console, I can't :


```
Uploads are disabled.
File uploads require push access to this repository.
```

I wish I could have push access, because I'm very accurate when it comes to thumbnails, and I want to add many missing files to some console.

Do you think you can give me access to help ?

Thank you.

**Comment by RobLoach** [comment]
Hmm, will likely need to make a fork first then :wink: 

![https://github-images.s3.amazonaws.com/help/bootcamp/Bootcamp-Fork.png](https://github-images.s3.amazonaws.com/help/bootcamp/Bootcamp-Fork.png)

**Comment by andiandi13** [comment]
@RobLoach Sure make sense. So when I update thumbnails in my forks, what happen ? You have to merge them to the master project manually ? Are you notified that there's new uploaded files in forks so that it's quick and easy to add them ?

I planned to update a good amount of thumbnails so...

**Comment by RobLoach** [comment]
I plan sure up there changes, btw ☺️

**Comment by andiandi13** [comment]
@RobLoach Alright. I also posted the same issue with a bunch of cover in the following repositories if you can merge them :

Nintendo - Game Boy

Nintendo - Game Boy Color

Nintendo - Game Boy Advance

Sega - Megadrive - Genesis

Nintendo - Nintendo Entertainment System

Next time I'll use pull requests.
